### ISSUE TITLE
Add a datapump

### ISSUE THREAD

**Issue by white-gecko** [Dockerizing/Pfarrerbuch.compose#4]
The setup needs a "datapump" to initially load data into the virtuoso from a git repository and to regularly or on update dump the changes to the git repository.

I could be integrated like that into the docker-compose file

```
  datapump:
    image: datapump
    container_name: pfarrerbuch_datapump
    environment:
    volumes:
      - /data/pfarrerbuch/models:/models
    links:
      - virtuoso
```

Maybe this is a candidate: https://github.com/Dockerizing/virtuoso-import-docker

**Comment by TBoonX** [comment]
With commit 2398f97 of virtuoso-import-docker you just need to add something like the following to your docker-compose file:

```
import:
        build: /path/to/repo
        command: /virtuoso/git_import.sh
        environment:
            DBA_PASSWORD: ${DBA_PASSWORD}
            VIRTUOSO_DATA_DIR: /virtuoso/data
            GIT_REPO: ${GIT_REPO}
            GRAPH_URI: ${GRAPH_URI}
            GIT_DIRECTORY: /virtuoso/git
            GIT_EMAIL: ${GIT_EMAIL}
            GIT_NAME: ${GIT_NAME}
        volumes:
            - files:/virtuoso/data
            - ./id_rsa:/root/.ssh/id_rsa
            - ./config:/root/.ssh/config

updater:
        build: /path/to/repo
        environment:
            DBA_PASSWORD: ${DBA_PASSWORD}
            VIRTUOSO_DATA_DIR: /virtuoso/data
            GIT_REPO: ${GIT_REPO}
            GRAPH_URI: ${GRAPH_URI}
            GIT_DIRECTORY: /virtuoso/git
            GIT_EMAIL: ${GIT_EMAIL}
            GIT_NAME: ${GIT_NAME}
            CRON_JOB: update
        volumes:
            - files:/virtuoso/data
            - ./id_rsa:/root/.ssh/id_rsa
            - ./config:/root/.ssh/config
```

In order to make sure the updater starts after import was finished, you need to use your own script or start the import by hand before the updater.
